[project]
name = "resumegenerator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "jinja2>=3.1.6",
    "pyyaml>=6.0.2",
    "weasyprint>=66.0",
]
